### PR TITLE
Remove versioning for install

### PR DESCRIPTION
**Pull request by dijonkitchen**
This may be confusing for newcomers. They won't know what version to put. 

Additionally, the Gemfile.lock handles the versioning so it's not needed unless there's a major version change and you don't want people to install it have breaking changes.

### CODE REVIEW

**Comment by dijonkitchen** [comment]
This is still relevant!

**Comment by dijonkitchen** [comment]
@maxd ?

**Comment by dijonkitchen** [comment]
@jlukic ?

**Comment by brendon** [comment]
I wonder is it possible to drive the version here from https://github.com/Semantic-Org/Semantic-UI-Rails-LESS/blob/master/lib/less/rails/semantic_ui/version.rb ? That way it'd automatically update.

**Comment by brendon** [comment]
That's true. I'm happy to accept this change.

**Pull request merged**
